// SPDX-License-Identifier: GPL-3.0-or-later
//
// Per-set constants, from the .mra's mod byte (ioctl index 1), latched during
// the download and static while the game runs.
//
// The SDRAM image (rtl/memory/gx_sdram_top.sv): maincpu packed at 0, then the
// k056832 region with its 5-byte rows spread to 8 at tile_base, the k055673
// region likewise at obj_base, sound after (Phase 3). The bases and the
// four-byte part sizes (region bytes / 5 * 4) are what scripts/build_mra.py
// derives from each set's ROM_START -- `python scripts/build_mra.py --cfg`
// prints this table, and every build of an .mra checks its set's arm against
// the ROM_START, so the two cannot drift apart silently.
//
// The video constants are MAME's (konamigx.cpp machine configs and
// konamigx_v.cpp): the tilemap layer offsets (common_init: the same
// -2, 0, 2, 3 for every set; tilemode 1, tbyahhoo/mtwinbee, only changes how
// MAME marks tilemaps dirty) and the mixer priority mode
// (konamigx_mixer_primode).

module gx_board_cfg (
    input       [7:0] game,
    output reg [25:0] tile_base,
    output reg [25:0] obj_base,
    output reg [23:0] tile_size4,   // k056832 four-byte part
    output reg [23:0] obj_size4,    // k055673 four-byte part
    output reg signed [7:0] offs_x [4],
    output reg signed [7:0] offs_y [4],
    output reg  [3:0] primode,
    output reg  [9:0] obj_hadj,     // K055673 set_config dx less daiskiss's -26, signed
    output reg        esc_gen,      // the ESC's run command calls generate_sprites
    output reg [23:0] esc_src,
    output reg  [8:0] esc_count
);

always @* begin
    offs_y = '{ 8'sd0, 8'sd0, 8'sd0, 8'sd0 };
    offs_x = '{ -8'sd2, 8'sd0, 8'sd2, 8'sd3 };
    primode = 4'd0;
    // konamigx.cpp gameDefs' special and the *_esc callbacks: daiskiss_esc and
    // tbyahhoo_esc walk 0x100 entries from 0xc00000, sexyparo_esc 0xfc from
    // 0xc00604; gokuparo, fantjour(a), crzcross and puzldama have none
    // (m_esc_cb null: the command only sets ESTATE_END and raises IRQ 4)
    esc_gen = 1'b0; esc_src = 24'hc00000; esc_count = 9'h100;
    // the K055673's x offset: konamigx() -26 (daiskiss, tbyahhoo, mtwinbee),
    // gokuparo() -46 (gokuparo, fantjour, fantjoura, crzcross, puzldama),
    // sexyparo() -42
    case( game )
        8'd1, 8'd2, 8'd3, 8'd4, 8'd5: obj_hadj = -10'sd20;
        8'd8, 8'd9:                   obj_hadj = -10'sd16;
        default:                      obj_hadj = 10'd0;
    endcase
    case( game )
        8'd0, 8'd6, 8'd7: esc_gen = 1'b1;                                          // daiskiss, mtwinbee, tbyahhoo
        8'd8, 8'd9:       begin esc_gen = 1'b1; esc_src = 24'hc00604; esc_count = 9'h0fc; end   // sexyparo(a)
        default: ;
    endcase
    case( game )
        // ---- generated by scripts/build_mra.py --cfg: begin
        8'd0:  begin tile_base = 26'h0200000; obj_base = 26'h0a00000; tile_size4 = 24'h400000; obj_size4 = 24'h400000; end  // daiskiss
        8'd1:  begin tile_base = 26'h0200000; obj_base = 26'h1200000; tile_size4 = 24'h800000; obj_size4 = 24'h400000; end  // crzcross
        8'd2:  begin tile_base = 26'h0200000; obj_base = 26'h1200000; tile_size4 = 24'h800000; obj_size4 = 24'h400000; end  // puzldama
        8'd3:  begin tile_base = 26'h0200000; obj_base = 26'h0c00000; tile_size4 = 24'h4ccccc; obj_size4 = 24'h400000; end  // fantjour
        8'd4:  begin tile_base = 26'h0200000; obj_base = 26'h0c00000; tile_size4 = 24'h4ccccc; obj_size4 = 24'h400000; end  // fantjoura
        8'd5:  begin tile_base = 26'h0200000; obj_base = 26'h0c00000; tile_size4 = 24'h4ccccc; obj_size4 = 24'h400000; end  // gokuparo
        8'd6:  begin tile_base = 26'h0200000; obj_base = 26'h0a00000; tile_size4 = 24'h400000; obj_size4 = 24'h400000; end  // mtwinbee
        8'd7:  begin tile_base = 26'h0200000; obj_base = 26'h0a00000; tile_size4 = 24'h400000; obj_size4 = 24'h400000; end  // tbyahhoo
        8'd8:  begin tile_base = 26'h0200000; obj_base = 26'h0a00000; tile_size4 = 24'h400000; obj_size4 = 24'h400000; end  // sexyparo
        8'd9:  begin tile_base = 26'h0200000; obj_base = 26'h0a00000; tile_size4 = 24'h400000; obj_size4 = 24'h400000; end  // sexyparoa
        // ---- generated: end
        default: begin tile_base = 26'h0200000; obj_base = 26'h0a00000; tile_size4 = 24'h400000; obj_size4 = 24'h400000; end
    endcase
    case( game )
        8'd0:        primode = 4'd4;                                   // daiskiss
        8'd1, 8'd2:  primode = 4'd5;                                   // crzcross, puzldama
        default: ;
    endcase
end

endmodule
