/*  jt054157_mmr.v was generated by jtframe mmr.
    Do not edit this generated file directly.
    Edit cfg/mmr.yaml or modules/jtframe/hdl/inc/mmr.v instead.
    Do not add generated *_mmr.v files to git. */

module jt054157_mmr(
    input             rst,
    input             clk,

    input             cs,
    input       [2:1] addr,
    input             rnw,
    input       [15:0] din, 
    output reg  [15:0] dout,
    input       [1:0] dsn,
    
    output       hofs_phase,
    output       clk_fanout,
    output       ram_clkph,
    output       a_hofs_flip,
    output       b_hofs_flip,
    output       c_hofs_flip,
    output       d_hofs_flip,
    output       ramout_mux,
    output       dbout_mux,
    output       vc_dir,
    output       crom_decode,
    output       db_lane,
    output       col_src0,
    output       col_src1,

    // IOCTL dump
    input      [2:0] ioctl_addr,
    output reg [7:0] ioctl_din,
    // Debug
    input      [7:0] debug_bus,
    output reg [7:0] st_dout
);

localparam SIZE=8;
parameter SIMFILE="rest.bin",
          SEEK=0;
parameter [SIZE*8-1:0] INIT=0; // from high to low regs {mmr[3],mmr[2],mmr[1],mmr[0]}


reg  [ 7:0] mmr[0:SIZE-1];
integer     i;
`ifdef SIMULATION
reg [7:0] mmr_init[0:SIZE-1];
`endif

assign hofs_phase = {
    mmr[0][0]
    };

assign clk_fanout = {
    mmr[0][3]
    };

assign ram_clkph = {
    mmr[0][4]
    };

assign a_hofs_flip = {
    mmr[2][0]
    };

assign b_hofs_flip = {
    mmr[2][2]
    };

assign c_hofs_flip = {
    mmr[2][4]
    };

assign d_hofs_flip = {
    mmr[2][6]
    };

assign ramout_mux = {
    mmr[4][3]
    };

assign dbout_mux = {
    mmr[4][4]
    };

assign vc_dir = {
    mmr[4][5]
    };

assign crom_decode = {
    mmr[4][6]
    };

assign db_lane = {
    mmr[6][5]
    };

assign col_src0 = {
    mmr[6][6]
    };

assign col_src1 = {
    mmr[6][7]
    };


always @(posedge clk) begin
    if( rst ) begin
    `ifndef SIMULATION
        for(i=0;i<SIZE;i=i+1) mmr[i] <= INIT[i*8+:8];
    `else
        for(i=0;i<SIZE;i=i+1) mmr[i] <= mmr_init[i];
    `endif 
    dout <= 0;
    end else begin
        dout      <= {mmr[{addr,1'b1}],mmr[{addr,1'b0}]};
        st_dout   <= mmr[debug_bus[2:0]];
        ioctl_din <= mmr[ioctl_addr];
        if( cs & ~rnw ) begin
            if(!dsn[0]) mmr[{addr,1'b0}]<=din[ 7:0];
            if(!dsn[1]) mmr[{addr,1'b1}]<=din[15:8];
        end
        i = 0; // for Quartus linter
    end
end

`ifdef SIMULATION
/* verilator tracing_off */
integer f, fcnt, err;
initial begin
    f=$fopen(SIMFILE,"rb");
    err=$fseek(f,SEEK,0);
    if( f!=0 && err!=0 ) begin
        $display("Cannot seek file rest.bin to offset 0x%0X (%0d)",SEEK,SEEK);
    end
    if( f!=0 ) begin
        fcnt=$fread(mmr_init,f);
        $display("MMR %m - read %0d bytes from offset %0d",fcnt,SEEK);
        if( fcnt!=SIZE ) begin
            $display("WARNING: Missing %d bytes for %m.mmr",SIZE-fcnt);
        end else begin
            $display("\thofs_phase = %X",{ mmr_init[0][0] });
            $display("\tclk_fanout = %X",{ mmr_init[0][3] });
            $display("\tram_clkph = %X",{ mmr_init[0][4] });
            $display("\ta_hofs_flip = %X",{ mmr_init[2][0] });
            $display("\tb_hofs_flip = %X",{ mmr_init[2][2] });
            $display("\tc_hofs_flip = %X",{ mmr_init[2][4] });
            $display("\td_hofs_flip = %X",{ mmr_init[2][6] });
            $display("\tramout_mux = %X",{ mmr_init[4][3] });
            $display("\tdbout_mux = %X",{ mmr_init[4][4] });
            $display("\tvc_dir = %X",{ mmr_init[4][5] });
            $display("\tcrom_decode = %X",{ mmr_init[4][6] });
            $display("\tdb_lane = %X",{ mmr_init[6][5] });
            $display("\tcol_src0 = %X",{ mmr_init[6][6] });
            $display("\tcol_src1 = %X",{ mmr_init[6][7] });
        end
    end else begin
        for(i=0;i<SIZE;i=i+1) mmr_init[i] = 0;
    end
    $fclose(f);
end
`endif

endmodule
