/*  jt054156_mmr.v was generated by jtframe mmr.
    Do not edit this generated file directly.
    Edit cfg/mmr.yaml or modules/jtframe/hdl/inc/mmr.v instead.
    Do not add generated *_mmr.v files to git. */

module jt054156_mmr(
    input             rst,
    input             clk,

    input             cs,
    input       [5:1] addr,
    input             rnw,
    input       [15:0] din, 
    output reg  [15:0] dout,
    input       [1:0] dsn,
    
    output [7:0] glob_ctrl,
    output [7:0] flip_en,
    output [7:0] attr_ctrl,
    output [7:0] irq_attr,
    output [7:0] addr_ctrl,
    output [7:0] lnscr_ctrl,
    output [5:0] vram_ctrl,
    output [5:0] a_vgrid,
    output [5:0] b_vgrid,
    output [5:0] c_vgrid,
    output [5:0] d_vgrid,
    output [5:0] a_hgrid,
    output [5:0] b_hgrid,
    output [5:0] c_hgrid,
    output [5:0] d_hgrid,
    output [10:0] a_scry,
    output [10:0] b_scry,
    output [10:0] c_scry,
    output [10:0] d_scry,
    output [11:0] a_scrx,
    output [11:0] b_scrx,
    output [11:0] c_scrx,
    output [11:0] d_scrx,
    output [5:0] lnscr_bank,
    output [5:0] cpu_bank,
    output [7:0] rom_bank,
    output [7:0] rom_col,
    output [1:0] rom_vrc,
    output [15:0] tile_lut,
    output [11:0] hflip_corr,
    output [10:0] vflip_corr,

    // IOCTL dump
    input      [5:0] ioctl_addr,
    output reg [7:0] ioctl_din,
    // Debug
    input      [7:0] debug_bus,
    output reg [7:0] st_dout
);

localparam SIZE=64;
parameter SIMFILE="rest.bin",
          SEEK=0;
parameter [SIZE*8-1:0] INIT=0; // from high to low regs {mmr[3],mmr[2],mmr[1],mmr[0]}


reg  [ 7:0] mmr[0:SIZE-1];
integer     i;
`ifdef SIMULATION
reg [7:0] mmr_init[0:SIZE-1];
`endif

assign glob_ctrl = {
    mmr[0][7:0]
    };

assign flip_en = {
    mmr[2][7:0]
    };

assign attr_ctrl = {
    mmr[4][7:0]
    };

assign irq_attr = {
    mmr[6][7:0]
    };

assign addr_ctrl = {
    mmr[8][7:0]
    };

assign lnscr_ctrl = {
    mmr[10][7:0]
    };

assign vram_ctrl = {
    mmr[12][5:0]
    };

assign a_vgrid = {
    mmr[16][5:0]
    };

assign b_vgrid = {
    mmr[18][5:0]
    };

assign c_vgrid = {
    mmr[20][5:0]
    };

assign d_vgrid = {
    mmr[22][5:0]
    };

assign a_hgrid = {
    mmr[24][5:0]
    };

assign b_hgrid = {
    mmr[26][5:0]
    };

assign c_hgrid = {
    mmr[28][5:0]
    };

assign d_hgrid = {
    mmr[30][5:0]
    };

assign a_scry = {
    mmr[33][2:0],
    mmr[32][7:0]
    };

assign b_scry = {
    mmr[35][2:0],
    mmr[34][7:0]
    };

assign c_scry = {
    mmr[37][2:0],
    mmr[36][7:0]
    };

assign d_scry = {
    mmr[39][2:0],
    mmr[38][7:0]
    };

assign a_scrx = {
    mmr[41][3:0],
    mmr[40][7:0]
    };

assign b_scrx = {
    mmr[43][3:0],
    mmr[42][7:0]
    };

assign c_scrx = {
    mmr[45][3:0],
    mmr[44][7:0]
    };

assign d_scrx = {
    mmr[47][3:0],
    mmr[46][7:0]
    };

assign lnscr_bank = {
    mmr[48][5:0]
    };

assign cpu_bank = {
    mmr[50][5:0]
    };

assign rom_bank = {
    mmr[52][7:0]
    };

assign rom_col = {
    mmr[53][7:0]
    };

assign rom_vrc = {
    mmr[54][1:0]
    };

assign tile_lut = {
    mmr[57][7:0],
    mmr[56][7:0]
    };

assign hflip_corr = {
    mmr[59][3:0],
    mmr[58][7:0]
    };

assign vflip_corr = {
    mmr[61][2:0],
    mmr[60][7:0]
    };


always @(posedge clk) begin
    if( rst ) begin
    `ifndef SIMULATION
        for(i=0;i<SIZE;i=i+1) mmr[i] <= INIT[i*8+:8];
    `else
        for(i=0;i<SIZE;i=i+1) mmr[i] <= mmr_init[i];
    `endif 
    dout <= 0;
    end else begin
        dout      <= {mmr[{addr,1'b1}],mmr[{addr,1'b0}]};
        st_dout   <= mmr[debug_bus[5:0]];
        ioctl_din <= mmr[ioctl_addr];
        if( cs & ~rnw ) begin
            if(!dsn[0]) mmr[{addr,1'b0}]<=din[ 7:0];
            if(!dsn[1]) mmr[{addr,1'b1}]<=din[15:8];
        end
        i = 0; // for Quartus linter
    end
end

`ifdef SIMULATION
/* verilator tracing_off */
integer f, fcnt, err;
initial begin
    f=$fopen(SIMFILE,"rb");
    err=$fseek(f,SEEK,0);
    if( f!=0 && err!=0 ) begin
        $display("Cannot seek file rest.bin to offset 0x%0X (%0d)",SEEK,SEEK);
    end
    if( f!=0 ) begin
        fcnt=$fread(mmr_init,f);
        $display("MMR %m - read %0d bytes from offset %0d",fcnt,SEEK);
        if( fcnt!=SIZE ) begin
            $display("WARNING: Missing %d bytes for %m.mmr",SIZE-fcnt);
        end else begin
            $display("\tglob_ctrl = %X",{ mmr_init[0][7:0] });
            $display("\tflip_en = %X",{ mmr_init[2][7:0] });
            $display("\tattr_ctrl = %X",{ mmr_init[4][7:0] });
            $display("\tirq_attr = %X",{ mmr_init[6][7:0] });
            $display("\taddr_ctrl = %X",{ mmr_init[8][7:0] });
            $display("\tlnscr_ctrl = %X",{ mmr_init[10][7:0] });
            $display("\tvram_ctrl = %X",{ mmr_init[12][5:0] });
            $display("\ta_vgrid = %X",{ mmr_init[16][5:0] });
            $display("\tb_vgrid = %X",{ mmr_init[18][5:0] });
            $display("\tc_vgrid = %X",{ mmr_init[20][5:0] });
            $display("\td_vgrid = %X",{ mmr_init[22][5:0] });
            $display("\ta_hgrid = %X",{ mmr_init[24][5:0] });
            $display("\tb_hgrid = %X",{ mmr_init[26][5:0] });
            $display("\tc_hgrid = %X",{ mmr_init[28][5:0] });
            $display("\td_hgrid = %X",{ mmr_init[30][5:0] });
            $display("\ta_scry = %X",{ mmr_init[33][2:0], mmr_init[32][7:0] });
            $display("\tb_scry = %X",{ mmr_init[35][2:0], mmr_init[34][7:0] });
            $display("\tc_scry = %X",{ mmr_init[37][2:0], mmr_init[36][7:0] });
            $display("\td_scry = %X",{ mmr_init[39][2:0], mmr_init[38][7:0] });
            $display("\ta_scrx = %X",{ mmr_init[41][3:0], mmr_init[40][7:0] });
            $display("\tb_scrx = %X",{ mmr_init[43][3:0], mmr_init[42][7:0] });
            $display("\tc_scrx = %X",{ mmr_init[45][3:0], mmr_init[44][7:0] });
            $display("\td_scrx = %X",{ mmr_init[47][3:0], mmr_init[46][7:0] });
            $display("\tlnscr_bank = %X",{ mmr_init[48][5:0] });
            $display("\tcpu_bank = %X",{ mmr_init[50][5:0] });
            $display("\trom_bank = %X",{ mmr_init[52][7:0] });
            $display("\trom_col = %X",{ mmr_init[53][7:0] });
            $display("\trom_vrc = %X",{ mmr_init[54][1:0] });
            $display("\ttile_lut = %X",{ mmr_init[57][7:0], mmr_init[56][7:0] });
            $display("\thflip_corr = %X",{ mmr_init[59][3:0], mmr_init[58][7:0] });
            $display("\tvflip_corr = %X",{ mmr_init[61][2:0], mmr_init[60][7:0] });
        end
    end else begin
        for(i=0;i<SIZE;i=i+1) mmr_init[i] = 0;
    end
    $fclose(f);
end
`endif

endmodule
